CREATE TABLE IF NOT EXISTS PATIENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    ID_CARD_NO VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    BIRTHDAY TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VISIT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VISIT_START_TIME TIMESTAMP,
    VISIT_END_TIME TIMESTAMP,
    DURATION VARCHAR(255),
    PATIENT_ID INT,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (ID)
);

CREATE TABLE IF NOT EXISTS FACILITY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    CITY VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    STREET VARCHAR(255),
    STREET_NO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DOCTOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    SPECIALISATION VARCHAR(255),
    FACILITY_ID INT,
    FOREIGN KEY (FACILITY_ID) REFERENCES FACILITY (ID)
);


INSERT INTO PATIENT (EMAIL, PASSWORD, ID_CARD_NO, FIRST_NAME, LAST_NAME, PHONE_NUMBER, BIRTHDAY) VALUES ('ssgg@gmail.com', 'aaaas', '1111', 'Szymon', 'Kowalski', '998' , '2001-09-01');
INSERT INTO PATIENT (EMAIL, PASSWORD, ID_CARD_NO, FIRST_NAME, LAST_NAME, PHONE_NUMBER, BIRTHDAY) VALUES ('sg@gmail.com', 'aaa', '111', 'Jan', 'Kowalski', '997' , '2000-09-01');
INSERT INTO PATIENT (EMAIL, PASSWORD, ID_CARD_NO, FIRST_NAME, LAST_NAME, PHONE_NUMBER, BIRTHDAY) VALUES ('test1@gmail.com', 'aaa2', '1111', 'Marcin', 'Kowalczyk', '133' , '1999-09-12');

INSERT INTO VISIT (VISIT_START_TIME, VISIT_END_TIME, DURATION, PATIENT_ID) VALUES ('2023-10-02 15:00:00', '2023-10-02 15:15:00', 1800000000000, 1);
INSERT INTO VISIT (VISIT_START_TIME, VISIT_END_TIME, DURATION, PATIENT_ID) VALUES ('2023-11-02 15:00:00', '2023-11-02 15:15:00', 1800000000000, NULL);

INSERT INTO FACILITY (NAME, CITY, POSTAL_CODE, STREET, STREET_NO) VALUES ('SZPITAL', 'Łódź', '93-817', 'Kaflowa', 87);

INSERT INTO DOCTOR (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, SPECIALISATION, FACILITY_ID) VALUES ('222@gmail.com', 'haslo111', 'Janek', 'Marciniak', 'NEUROLOGY', 1);
INSERT INTO DOCTOR (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, SPECIALISATION) VALUES ('sz1@gmail.com', 'hasl11', 'Maria', 'Wrona', 'ONCOLOGY');